name: Publish development release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release_development_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 8512546
          log-accepted-android-sdk-licenses: true

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build APKs
        run: ./gradlew assembleFdroidDebug assemblePlayStoreDebug

      - name: Set environment variables
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "SHA_SHORT=$SHA_SHORT" >> $GITHUB_ENV

          # Find generated APKs dynamically
          APK_FDROID=$(find app/build/outputs/apk/fdroid/debug -name "*.apk" | head -n 1)
          APK_PLAYSTORE=$(find app/build/outputs/apk/playStore/debug -name "*.apk" | head -n 1)

          echo "APK_PATH_FDROID=$(dirname $APK_FDROID)" >> $GITHUB_ENV
          echo "APK_PATH_PLAYSTORE=$(dirname $APK_PLAYSTORE)" >> $GITHUB_ENV
          echo "APK_NAME_FDROID=LRC.Editor.Dev.Debug.FDroid.$SHA_SHORT.apk" >> $GITHUB_ENV
          echo "APK_NAME_PLAYSTORE=LRC.Editor.Dev.Debug.PlayStore.$SHA_SHORT.apk" >> $GITHUB_ENV

      - name: Rename APKs
        run: |
          mv $APK_PATH_FDROID/*.apk $APK_PATH_FDROID/$APK_NAME_FDROID
          mv $APK_PATH_PLAYSTORE/*.apk $APK_PATH_PLAYSTORE/$APK_NAME_PLAYSTORE

      - name: Cleanup v-dev tag and release
        run: gh release delete v-dev --cleanup-tag --yes || true
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload APKs to GitHub release
        run: |
          gh release create v-dev \
            $APK_PATH_FDROID/$APK_NAME_FDROID \
            $APK_PATH_PLAYSTORE/$APK_NAME_PLAYSTORE \
            --title "LRC Editor Developer Build" \
            --notes "Unreleased developer build with latest updates (FDroid & PlayStore debug variants)" \
            --target ${{ github.sha }} \
            --prerelease
        env:
          GH_TOKEN: ${{ github.token }}
